### ISSUE TITLE
ui: Map is missing all data in display

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-front#65] opened 2019-01-25 01:02 UTC
Map feature is missing all map data (http://encyclopedia.densho.org/map/). Maybe a side-effect of ES change?

**Comment by gjost** [comment] 2019-01-25 01:32
`encycfront` is hitting the `encycedit` server for the locations data, but `http GET` from withing the cluster returns `Invalid HTTP_HOST header: 'IPADDR:PORT'. You may need to add u'IPADDR' to ALLOWED_HOSTS.```

**Comment by gjost** [comment] 2019-01-25 01:40
Updated `ALLOWED_HOSTS`, now http://IPADDR:PORT/api/v1.0/locations/ returns a 404.

**Comment by gjost** [comment] 2019-01-25 17:46
It looks like the problem is that much of the `encyc-psms` API is disabled, including the locations URL that `encyc-front` is trying to hit here.

Looks like I commented out the API functions while upgrading `encyc-psms` to Django 1.11 and neglected to re-enable it.  `encyc-psms` is our oldest codebase and the API uses `django-tastypie` instead of `django-rest-framework`.  I'm guessing that I disabled it because it conflicted with other dependencies.

The fix will be in `encyc-psms`: https://github.com/densho/encyc-psms/issues/9

**Closed by gjost** 2019-01-25 17:46 UTC
Labels: bug, important
